export const Seo = {
	Title: {
		new: '새로운 지원서',
		newComplete: '지원서 생성 완료',
		edit: '지원서 수정',
		main: '지원서 관리',
		reply: '지원서 작성',
		replyComplete: '지원서 작성 완료',
		replyClosed: '지원서 모집 마감',
		view: '지원서 조회',
		register: '회원가입',
		registerClub: '신규 동아리 등록',
		registerClubComplete: '신규 동아리 등록 완료',
		registerMemberCode: '동아리 코드 입력',
		registerMember: '동아리 운영진 가입',
		registerMemberComplete: '동아리 운영진 가입 완료',
		login: '로그인',
		landing: 'About',
	},
} as const;
